version: '3.4'
services:
  bot:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    environment:
      ConnectionStrings__DefaultDbContext: Host=db;Database=cod;Username=postgres;Password=postgres
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cod
    ports:
    - 5432:5432 