version: '3.4'

services:
  bot:
    image: ${DOCKER_REGISTRY-}discord-cod
    environment:
        ConnectionStrings__DefaultDbContext: Host=db;Database=cod;Username=postgres;Password=postgres
    build:
      context: .
      dockerfile: DiscordChannelsOnDemand.Bot/Dockerfile

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cod
