# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v1.8.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Build Image
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./src
          file: ./src/DiscordVoiceChannelsOnDemand.Bot/Dockerfile
          tags: ginomessmer/discord-vcod:latest
          push: true
