name: Docker Release Build

on:
  push:
    branches: [ main ]

  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v1.8.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./src
          file: ./src/DiscordChannelsOnDemand.Bot/Dockerfile
          tags: ginomessmer/discord-vcod:latest,ginomessmer/discord-vcod:${{ github.run_id }}
          push: true
